//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skilled
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabSklad
    {
        public int TabSkladId { get; set; }
        public Nullable<int> N_nn { get; set; }
        public Nullable<int> TabGroupRef { get; set; }
        public string Назва { get; set; }
        public Nullable<int> TabVyrobnykRef { get; set; }
        public Nullable<decimal> Ціна { get; set; }
        public Nullable<int> Кількість { get; set; }
        public string Постачальник { get; set; }
        public Nullable<int> TabValutaRef { get; set; }
        public Nullable<int> TabSkladRef { get; set; }
    
        public virtual TabGrupa TabGrupa { get; set; }
        public virtual TabSklad_2 TabSklad_2 { get; set; }
        public virtual TabValuta TabValuta { get; set; }
        public virtual TabVyrobnyk TabVyrobnyk { get; set; }
    }
}
